1. Import the numpy package under the name np 

In [2]:
import numpy as np

2. Create a null vector of size 20

In [3]:
vector1 = np.zeros(20)
vector1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Create a null vector of size 10 but the second value which is 1 

In [7]:
vector1 = np.zeros(10)
vector1[1]=1
vector1

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

4. Create a vector with values ranging from 10 to 49

In [9]:
vector1 = np.arange(10,50,1)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5 Reverse a vector (first element becomes last

In [11]:
vector = np.array([3,4,7,8,9,2])
reverse = vector[::-1]
reverse

array([2, 9, 8, 7, 4, 3])

6 Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7 Create a 3x3x3 array with random values 

In [3]:
np.random.rand(3,3,3)

array([[[0.16290259, 0.16707625, 0.1404496 ],
        [0.0035836 , 0.13244138, 0.16343701],
        [0.50469489, 0.17656961, 0.32338629]],

       [[0.76137273, 0.6098381 , 0.32313227],
        [0.71081245, 0.20628816, 0.32741586],
        [0.77369644, 0.96029078, 0.20497177]],

       [[0.54036588, 0.53006326, 0.77157331],
        [0.93964518, 0.92509467, 0.67023   ],
        [0.5423994 , 0.93673436, 0.06281145]]])

8. Create a 10x10 array with random values and find the minimum and maximum values


In [10]:
vector = np.random.rand(10,10)
print(vector)
print('\n')
print(vector.min())
print(vector.max())

[[0.30228587 0.38124807 0.01777268 0.48490911 0.36918897 0.37389432
  0.46369715 0.04638367 0.79710307 0.10058427]
 [0.93535058 0.71253845 0.14879664 0.72940139 0.58423605 0.09165169
  0.4890191  0.83127145 0.31076352 0.86987096]
 [0.83725233 0.22830006 0.23491661 0.07748836 0.0564732  0.49174832
  0.81224787 0.58717279 0.72712637 0.32198521]
 [0.03652039 0.91347423 0.67308053 0.09701369 0.18011149 0.02271859
  0.91438312 0.97591158 0.1089896  0.52622068]
 [0.63043175 0.5086749  0.78837775 0.16744045 0.67798323 0.47433696
  0.06405125 0.18313189 0.61803355 0.26999411]
 [0.66143017 0.99033562 0.77177456 0.62624565 0.1203419  0.61339491
  0.40051274 0.46245218 0.79911692 0.88399726]
 [0.16345156 0.91599692 0.33816612 0.00334445 0.43289422 0.82434517
  0.37199892 0.55203854 0.89151255 0.55565508]
 [0.39278159 0.04586836 0.88298708 0.58502602 0.78913154 0.11269379
  0.5010918  0.84621429 0.93756675 0.31345757]
 [0.34600225 0.16154028 0.41221442 0.38417247 0.28472924 0.42819734
  0.16621894

9 Create a 5x5 matrix with row values ranging from 0 to 4 

In [12]:
vector =np.arange(0,5)
vector

array([0, 1, 2, 3, 4])

10 Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [25]:
np.linspace(0,1,10,endpoint=True)[1:-1]

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

11. Create a random vector of size 10 and sort it 


In [16]:
x = np.random.random(10)
print(vector)
x.sort()


[ 8 18 23 46 47 53 62 76 81 83]


12 How to convert a float (32 bits) array into an integer (32 bits) in place?

In [25]:
x= np.array([3,5,3.5,7.9,2.2,7.5],dtype='f')
print(x)
newarr=x.astype('i')
newarr

[3.  5.  3.5 7.9 2.2 7.5]


array([3, 5, 3, 7, 2, 7], dtype=int32)

13 How to swap two rows of an array?

In [36]:
a = np.array([[3,4,5],[8,9,0]])
a[[0,1]]=a[[1,0]]
print(a)

[[8 9 0]
 [3 4 5]]


14 How to find the most frequent value in an array?


In [41]:
y = np.array([2,5,3,2,8,7,2])
np.bincount(y).argmax()

2

15  How to reshape an array?

In [52]:
arr = np.array([[1,2,4,5,8,9,0,9]])
newarr = arr.reshape(2,2,2)
newarr

array([[[1, 2],
        [4, 5]],

       [[8, 9],
        [0, 9]]])

16. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

val1: 7
val2: 3

In [64]:
var1 = 7
var2 = 3
print(np.add(var1,var2))
print(np.subtract(var1,var2))
print(np.multiply(var1,var2))
print(np.divide(var1,var2))

10
4
21
2.3333333333333335


17 Write a NumPy program to calculate the absolute value element-wise.

[-10.2, 122.2, -.20]

In [66]:
arr = np.array([-10.2,122.2,-0.20])
print(np.fabs(arr))

[ 10.2 122.2   0.2]


18 Write a NumPy program to round elements of the array to the nearest integer.
[-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0]   

In [69]:
arr = np.array([-0.7,-1.5,-1.7,0.3,1.5,1.8,2.0])
print(np.rint(arr))

[-1. -2. -2.  0.  2.  2.  2.]


19 Write a NumPy program to compute the mean, average of given array .

[0 1 2 3 4 5]

In [73]:
arr= np.array([0,1,2,3,4,5])
print(np.mean(arr))
print(np.average(arr))


2.5
2.5


20 Write a NumPy program to compute  standard deviation, and variance of a given array .

[2,4,6,7,8]

In [75]:
arr = np.array([2,4,6,7,8])
print(np.std(arr))
print(np.var(arr))

2.1540659228538015
4.64
