# NUMPY

NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matric

#### Arrays can store data very compactly and are more efficient for storing large amounts of data. Arrays are great for numerical operations; lists cannot directly handle math operations

# Difference Btwn List and array

#### A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 

#### A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

# In List we can pass different datatypes but in array we can only give similar Datatypes

# Creating Array

In [1]:
import numpy as np

In [2]:
#with list
arr = np.array([1,2,4,6,8])

arr

array([1, 2, 4, 6, 8])

In [3]:
#check data type
type(arr)

numpy.ndarray

In [4]:
# with tuple
arr = np.array((1, 2, 3, 4, 5))

arr

array([1, 2, 3, 4, 5])

In [5]:
#add list into np
lis=[1,2,4,6,8]

arr=np.array(lis)
arr

array([1, 2, 4, 6, 8])

In [6]:
arr


array([1, 2, 4, 6, 8])

In [7]:
#Return a new array of given shape and type, with random values..


a = np.empty([2,2], dtype = int) 
a

array([[ 1245112013, -1327779541],
       [ -107563019,  -207799191]])

In [3]:
#The numpy.ones() function returns a new array of given shape and type, with ones.
a = np.zeros(4) 
a

array([ 0.,  0.,  0.,  0.])

In [2]:
a = np.zeros((5,2), dtype = int) 
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [10]:
#create array with ones
a = np.ones(5) 
a

array([1., 1., 1., 1., 1.])

In [11]:
#create array with range
a = np.arange(4) 
a

array([0, 1, 2, 3])

 Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop,step)

In [12]:
#with condition 
a = np.arange(10,30,2) 
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [4]:
#using line space, number of sample =5
a = np.linspace(10,30,5) 
a

array([ 10.,  15.,  20.,  25.,  30.])

# Dimension

In [14]:
#Zero dimension
arr = np.array(42)

print(arr)
 
print(arr.ndim)

42
0


In [15]:
#one dimension
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(arr.ndim)

[1 2 3 4 5]
1


More than one dimension:

In [16]:
#Two dimension

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [17]:
#Three dimension

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [18]:
#multiple dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim)


[[[[[1 2 3 4]]]]]
5


In [19]:
#random method to creat array
a = np.random.rand()
a

0.5595612952294106

Random sampling in numpy | randint() function

In [20]:
a = np.random.randint(20, size=(4))

a

array([ 3,  5, 15,  8])

In [21]:
a = np.random.rand(4)

a

array([0.8550414 , 0.27085811, 0.25866745, 0.40218101])

In [22]:
a = np.random.rand(2,2)

a


array([[0.84494787, 0.82009985],
       [0.06727487, 0.75462263]])

Return one of the values in an array:

In [23]:

a = np.random.choice([1,2,3,4,5])

a

5

Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [24]:
a = np.random.choice([3, 5, 7, 9], size=(1, 2))

a

array([[5, 7]])

# Data type

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [8]:
#int
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [9]:
#string
arr = np.array(['python', 'java', 'c'])

print(arr.dtype)

<U6


In [79]:
#convert data type
arr = np.array([12.3,16.34,21.34])

new_arr = arr.astype('i')


array([12, 16, 21], dtype=int32)

In [28]:
print(arr)
print(new_arr)
print(new_arr.dtype)

[12.3  16.34 21.34]
[12 16 21]
int32


In [29]:
arr = np.array([4, 0, 2])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# COPY Array

In [30]:
arr = np.array([10,20,30,40,50])
a = arr.copy()

In [31]:
print(arr)
print(a)

[10 20 30 40 50]
[10 20 30 40 50]


Make a view, change the original array, and display both arrays

In [32]:
#view, changing in view array affect orignal arrray

arr = np.array([10,20,30,40,50])
a = arr.view()
arr[0] = 100

In [33]:
print(arr)
print(a)

[100  20  30  40  50]
[100  20  30  40  50]


# Indexing & slicing

In [34]:
arr = np.array([10,20,30,40,50])

arr[0]

10

In [35]:

arr[1]

20

In [36]:
import numpy as np
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print(arr)
arr[0, 1]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


20

In [37]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
arr[0, -2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


4

In [38]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [39]:
arr[:2,:3]


array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
arr[2:,3:]


array([[8, 9]])

In [41]:
arr[:,3:]


array([[4, 5],
       [5, 6],
       [8, 9]])

# Shape

In [42]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr.shape


(2, 4)

In [43]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
arr.shape


[[[1 2 3 4]]]


(1, 1, 4)

# Reshape

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

print("     ")

new_arr = arr.reshape(4, 3)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
     
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(2, 2, 3)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# iterating

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])

In [48]:
for i in np.nditer(arr):
   print(i),

1
2
3
4
5
2
3
4
5
6
9
7
6
8
9


# Transpose  array

rotate array 

In [49]:

print(arr)

print("__________")

Tran_arry  = arr.T 

print(Tran_arry)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
__________
[[1 2 9]
 [2 3 7]
 [3 4 6]
 [4 5 8]
 [5 6 9]]


# sorting 

In [50]:
arr = np.array([7,2,23,15,11])
print(arr)
print(np.sort(arr))

[ 7  2 23 15 11]
[ 2  7 11 15 23]


In [51]:
#two dim array sort
arr = np.array([[20,10], [3,7]])
new_arr = np.sort(arr)        
new_arr

array([[10, 20],
       [ 3,  7]])

In [52]:
#sorting by axis , row ,column
arr = np.array([[20,10], [3,7]])
print(arr)
new_arr = np.sort(arr, axis = 0) 
new_arr

[[20 10]
 [ 3  7]]


array([[ 3,  7],
       [20, 10]])

# Searching

In [53]:
arr = np.array([2,2,5,7,8,2,5,9])

x = np.where(arr == 2)

print(x)

(array([0, 1, 5], dtype=int64),)


# Splitting 

In [54]:
arr = np.array([2,2,5,7,8,2,5,9])

newarr = np.array_split(arr, 4)

print(newarr)


[array([2, 2]), array([5, 7]), array([8, 2]), array([5, 9])]


# joining

In [55]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.concatenate((arr, arr1))

arr

array([ 2,  4,  6,  8, 10, 12])

In [56]:
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=0) 

arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [57]:
#try with 1
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=1)

arr

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [58]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.hstack((arr, arr1))

arr


array([ 2,  4,  6,  8, 10, 12])

In [59]:

arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.vstack((arr, arr1))

arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [60]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


arr = np.dstack((arr, arr1))

arr

array([[[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

# String , arithmmetic , static opration

In [61]:
arr = np.array(["USA","INDIA","RUSSIA"])

new_arr = np.char.lower(arr)

new_arr

array(['usa', 'india', 'russia'], dtype='<U6')

In [62]:
arr= np.char.join('&', 'FINGERTIPS')
arr

array('F&I&N&G&E&R&T&I&P&S', dtype='<U19')

In [63]:
arr = np.array([2.344,6.232,8.34,5,3.5,4.36]) 

np.around(arr) 

array([2., 6., 8., 5., 4., 4.])

In [64]:
np.around(arr, decimals = 1) 

array([2.3, 6.2, 8.3, 5. , 3.5, 4.4])

In [65]:
np.floor(arr)

array([2., 6., 8., 5., 3., 4.])

In [66]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


In [67]:
np.add(arr,arr1) 

array([10, 14, 18])

In [68]:
np.subtract(arr,arr1) 

array([-6, -6, -6])

In [69]:
np.multiply(arr,arr1) 

array([16, 40, 72])

In [70]:
np.divide(arr1,arr)

array([4. , 2.5, 2. ])

In [71]:
np.power(arr,2) 

array([ 4, 16, 36], dtype=int32)

In [72]:
np.mod(arr1,arr) 

array([0, 2, 0], dtype=int32)

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [74]:
np.median(arr) 

6.5

In [75]:
np.mean(arr) 

6.5

In [76]:
np.average(arr) 

6.5

In [77]:
np.std(arr)

3.452052529534663

In [78]:
np.var(arr)

11.916666666666666